vanished: []
fullvanished: []
modmode: []
allow:
  flight: true
bperms:
  enabled: true
  modmodegroup: ModMode
groupmap: !!map {}
debug:
  playerdata: false
commands:
  activate:
    before: []
    after:
    - /we cui
    - /lb toolblock on
  deactivate:
    before: []
    after: []
    
