name: ModMode
version: ${project.version}
description: ${project.description}

authors: [Travis Watkins, Deaygo]
website: ${project.url}

main: nu.nerd.modmode.ModMode
softdepend: [bPermissions, TagAPI, LogBlock]
depend: [VanishNoPacket]

commands:
  vanish:
    description: Vanish, or check vanish state with /vanish check.
    permission: modmode.vanish
  unvanish:
    description: Unvanish.
    permission: modmode.unvanish
  vanishlist:
    description: Show list of invisible people
    permission: modmode.vanishlist
  modmode:
    description: Toggle ModMode
    permission: modmode.toggle

permissions:
  modmode:
    description: Allow the player all Vanish-related permissions
    children:
      modmode.vanishlist:
        description: Allow the player to see the vanish list
  modmode.toggle:
    description: Allow the player to enter ModMode
